<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>MobilniKucharka</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Mobilní Kuchařka</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.ondymikula.mobilnikucharka</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.6</ApplicationDisplayVersion> <!-- Co vidí user (1.6), "- beta" pro oznaceni beta verze -->
		<ApplicationVersion>14</ApplicationVersion> <!-- +1 KDYZ CHCES VYDAT NOVOU VERZI	(14) -->

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>

		<PackageReadmeFile>README.md</PackageReadmeFile>

		<PackageIcon>appicon.png</PackageIcon>

		<RepositoryUrl>https://github.com/OndyMikula/MobilniKucharka</RepositoryUrl>
		
	</PropertyGroup>

	<PropertyGroup Condition="'$(AndroidSdkDirectory)' == '' and Exists('D:\Program Files (x86)\Microsoft Visual Studio\Shared\Android\android-sdk')">
		<AndroidSdkDirectory>D:\Program Files (x86)\Microsoft Visual Studio\Shared\Android\android-sdk</AndroidSdkDirectory>
		<JavaSdkDirectory>D:\Program Files (x86)\Microsoft Visual Studio\Shared\Android\openjdk\jdk-21.0.8</JavaSdkDirectory>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-android|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" Color="#512BD4" ForegroundScale="0.7" />	
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\AppIcon\appicon.png" Color="#2196F3" BaseSize="300,300" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.100" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
		<PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.90" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Classes\Legal\LegalDocumentPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Classes\Legal\LicensePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Classes\UserData\OnBoardingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Classes\UserData\SettingsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Classes\Navigation\BlazorShellPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Resources\AppIcon\appicon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
